from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionObjet = QAction(MainWindow)
        self.actionObjet.setObjectName(u"actionObjet")
        self.actionReset_Sc_ne = QAction(MainWindow)
        self.actionReset_Sc_ne.setObjectName(u"actionReset_Sc_ne")
        self.actionAjouter_Frame_apr_s = QAction(MainWindow)
        self.actionAjouter_Frame_apr_s.setObjectName(u"actionAjouter_Frame_apr_s")
        self.actionAjouter_Frame_d_but = QAction(MainWindow)
        self.actionAjouter_Frame_d_but.setObjectName(u"actionAjouter_Frame_d_but")
        self.actionAjouter_Frame_fin = QAction(MainWindow)
        self.actionAjouter_Frame_fin.setObjectName(u"actionAjouter_Frame_fin")
        self.actionFPS = QAction(MainWindow)
        self.actionFPS.setObjectName(u"actionFPS")
        self.actionAvant = QAction(MainWindow)
        self.actionAvant.setObjectName(u"actionAvant")
        self.actionApr_s = QAction(MainWindow)
        self.actionApr_s.setObjectName(u"actionApr_s")
        self.actionD_but = QAction(MainWindow)
        self.actionD_but.setObjectName(u"actionD_but")
        self.actionFin = QAction(MainWindow)
        self.actionFin.setObjectName(u"actionFin")
        self.actionToggle_Loop = QAction(MainWindow)
        self.actionToggle_Loop.setObjectName(u"actionToggle_Loop")
        self.actionManu = QAction(MainWindow)
        self.actionManu.setObjectName(u"actionManu")
        self.actionS_lectionner = QAction(MainWindow)
        self.actionS_lectionner.setObjectName(u"actionS_lectionner")
        self.actionOn = QAction(MainWindow)
        self.actionOn.setObjectName(u"actionOn")
        self.actionOff = QAction(MainWindow)
        self.actionOff.setObjectName(u"actionOff")
        self.actionFull = QAction(MainWindow)
        self.actionFull.setObjectName(u"actionFull")
        self.actionMinimale = QAction(MainWindow)
        self.actionMinimale.setObjectName(u"actionMinimale")
        self.actionOff_2 = QAction(MainWindow)
        self.actionOff_2.setObjectName(u"actionOff_2")
        self.actionOn_2 = QAction(MainWindow)
        self.actionOn_2.setObjectName(u"actionOn_2")
        self.actionOff_3 = QAction(MainWindow)
        self.actionOff_3.setObjectName(u"actionOff_3")
        self.actionOn_3 = QAction(MainWindow)
        self.actionOn_3.setObjectName(u"actionOn_3")
        self.actionOff_4 = QAction(MainWindow)
        self.actionOff_4.setObjectName(u"actionOff_4")
        self.actionSauvegarder = QAction(MainWindow)
        self.actionSauvegarder.setObjectName(u"actionSauvegarder")
        self.actionAjouter_ici = QAction(MainWindow)
        self.actionAjouter_ici.setObjectName(u"actionAjouter_ici")
        self.actionAjouter_d_but = QAction(MainWindow)
        self.actionAjouter_d_but.setObjectName(u"actionAjouter_d_but")
        self.actionAjouter_fin = QAction(MainWindow)
        self.actionAjouter_fin.setObjectName(u"actionAjouter_fin")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionSauvegarder_2 = QAction(MainWindow)
        self.actionSauvegarder_2.setObjectName(u"actionSauvegarder_2")
        self.actionSauvegarder_3 = QAction(MainWindow)
        self.actionSauvegarder_3.setObjectName(u"actionSauvegarder_3")
        self.actionCharger_2 = QAction(MainWindow)
        self.actionCharger_2.setObjectName(u"actionCharger_2")
        self.actionBackground = QAction(MainWindow)
        self.actionBackground.setObjectName(u"actionBackground")
        self.actionTaille_Sc_ne = QAction(MainWindow)
        self.actionTaille_Sc_ne.setObjectName(u"actionTaille_Sc_ne")
        self.action_9 = QAction(MainWindow)
        self.action_9.setObjectName(u"action_9")
        self.action_10 = QAction(MainWindow)
        self.action_10.setObjectName(u"action_10")
        self.actionFit = QAction(MainWindow)
        self.actionFit.setObjectName(u"actionFit")
        self.actionCenter = QAction(MainWindow)
        self.actionCenter.setObjectName(u"actionCenter")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menuReset = QMenu(self.menubar)
        self.menuReset.setObjectName(u"menuReset")
        self.menuAjouter_Marionnette = QMenu(self.menuReset)
        self.menuAjouter_Marionnette.setObjectName(u"menuAjouter_Marionnette")
        self.menuToggle_Inspector = QMenu(self.menuReset)
        self.menuToggle_Inspector.setObjectName(u"menuToggle_Inspector")
        self.menuToggle_Timeline = QMenu(self.menuReset)
        self.menuToggle_Timeline.setObjectName(u"menuToggle_Timeline")
        self.menuToggle_Transformation = QMenu(self.menuReset)
        self.menuToggle_Transformation.setObjectName(u"menuToggle_Transformation")
        self.menuTimeline = QMenu(self.menubar)
        self.menuTimeline.setObjectName(u"menuTimeline")
        self.menuAjouter_Frame = QMenu(self.menuTimeline)
        self.menuAjouter_Frame.setObjectName(u"menuAjouter_Frame")
        self.menuToggle_Loop = QMenu(self.menuTimeline)
        self.menuToggle_Loop.setObjectName(u"menuToggle_Loop")
        self.menuAnimations = QMenu(self.menubar)
        self.menuAnimations.setObjectName(u"menuAnimations")
        self.menuCharger = QMenu(self.menuAnimations)
        self.menuCharger.setObjectName(u"menuCharger")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuZoom = QMenu(self.menubar)
        self.menuZoom.setObjectName(u"menuZoom")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuReset.menuAction())
        self.menubar.addAction(self.menuTimeline.menuAction())
        self.menubar.addAction(self.menuAnimations.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuZoom.menuAction())
        self.menuReset.addAction(self.menuAjouter_Marionnette.menuAction())
        self.menuReset.addAction(self.actionObjet)
        self.menuReset.addSeparator()
        self.menuReset.addSeparator()
        self.menuReset.addAction(self.menuToggle_Inspector.menuAction())
        self.menuReset.addAction(self.menuToggle_Timeline.menuAction())
        self.menuReset.addAction(self.menuToggle_Transformation.menuAction())
        self.menuReset.addSeparator()
        self.menuReset.addSeparator()
        self.menuReset.addAction(self.actionReset_Sc_ne)
        self.menuAjouter_Marionnette.addAction(self.actionManu)
        self.menuAjouter_Marionnette.addAction(self.actionS_lectionner)
        self.menuToggle_Inspector.addAction(self.actionOn)
        self.menuToggle_Inspector.addAction(self.actionOff)
        self.menuToggle_Timeline.addAction(self.actionFull)
        self.menuToggle_Timeline.addAction(self.actionMinimale)
        self.menuToggle_Timeline.addAction(self.actionOff_2)
        self.menuToggle_Transformation.addAction(self.actionOn_2)
        self.menuToggle_Transformation.addAction(self.actionOff_3)
        self.menuTimeline.addAction(self.menuAjouter_Frame.menuAction())
        self.menuTimeline.addSeparator()
        self.menuTimeline.addAction(self.actionFPS)
        self.menuTimeline.addSeparator()
        self.menuTimeline.addSeparator()
        self.menuTimeline.addAction(self.menuToggle_Loop.menuAction())
        self.menuTimeline.addSeparator()
        self.menuTimeline.addAction(self.actionSauvegarder_3)
        self.menuTimeline.addAction(self.actionCharger_2)
        self.menuAjouter_Frame.addAction(self.actionAvant)
        self.menuAjouter_Frame.addAction(self.actionApr_s)
        self.menuAjouter_Frame.addAction(self.actionD_but)
        self.menuAjouter_Frame.addAction(self.actionFin)
        self.menuToggle_Loop.addAction(self.actionOn_3)
        self.menuToggle_Loop.addAction(self.actionOff_4)
        self.menuAnimations.addAction(self.menuCharger.menuAction())
        self.menuAnimations.addAction(self.actionSauvegarder)
        self.menuAnimations.addAction(self.actionUndo)
        self.menuAnimations.addAction(self.actionRedo)
        self.menuCharger.addAction(self.actionAjouter_ici)
        self.menuCharger.addAction(self.actionAjouter_d_but)
        self.menuCharger.addAction(self.actionAjouter_fin)
        self.menuOptions.addAction(self.actionBackground)
        self.menuOptions.addAction(self.actionTaille_Sc_ne)
        self.menuZoom.addAction(self.action_9)
        self.menuZoom.addAction(self.action_10)
        self.menuZoom.addAction(self.actionFit)
        self.menuZoom.addAction(self.actionCenter)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionObjet.setText(QCoreApplication.translate("MainWindow", u"Ajouter Objet", None))
        self.actionReset_Sc_ne.setText(QCoreApplication.translate("MainWindow", u"Reset Sc\u00e8ne", None))
        self.actionAjouter_Frame_apr_s.setText(QCoreApplication.translate("MainWindow", u"Ajouter Frame apr\u00e8s", None))
        self.actionAjouter_Frame_d_but.setText(QCoreApplication.translate("MainWindow", u"Ajouter Frame d\u00e9but", None))
        self.actionAjouter_Frame_fin.setText(QCoreApplication.translate("MainWindow", u"Ajouter Frame fin", None))
        self.actionFPS.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.actionAvant.setText(QCoreApplication.translate("MainWindow", u"Avant", None))
        self.actionApr_s.setText(QCoreApplication.translate("MainWindow", u"Apr\u00e8s", None))
        self.actionD_but.setText(QCoreApplication.translate("MainWindow", u"D\u00e9but", None))
        self.actionFin.setText(QCoreApplication.translate("MainWindow", u"Fin", None))
        self.actionToggle_Loop.setText(QCoreApplication.translate("MainWindow", u"Toggle Loop", None))
        self.actionManu.setText(QCoreApplication.translate("MainWindow", u"Manu", None))
        self.actionS_lectionner.setText(QCoreApplication.translate("MainWindow", u"S\u00e9lectionner", None))
        self.actionOn.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.actionOff.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.actionFull.setText(QCoreApplication.translate("MainWindow", u"Full", None))
        self.actionMinimale.setText(QCoreApplication.translate("MainWindow", u"Minimale", None))
        self.actionOff_2.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.actionOn_2.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.actionOff_3.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.actionOn_3.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.actionOff_4.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.actionSauvegarder.setText(QCoreApplication.translate("MainWindow", u"Sauvegarder", None))
        self.actionAjouter_ici.setText(QCoreApplication.translate("MainWindow", u"Ajouter ici", None))
        self.actionAjouter_d_but.setText(QCoreApplication.translate("MainWindow", u"Ajouter d\u00e9but", None))
        self.actionAjouter_fin.setText(QCoreApplication.translate("MainWindow", u"Ajouter fin", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionSauvegarder_2.setText(QCoreApplication.translate("MainWindow", u"Sauvegarder", None))
        self.actionSauvegarder_3.setText(QCoreApplication.translate("MainWindow", u"Sauvegarder", None))
        self.actionCharger_2.setText(QCoreApplication.translate("MainWindow", u"Charger", None))
        self.actionBackground.setText(QCoreApplication.translate("MainWindow", u"Background", None))
        self.actionTaille_Sc_ne.setText(QCoreApplication.translate("MainWindow", u"Taille Sc\u00e8ne", None))
        self.action_9.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.action_10.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.actionFit.setText(QCoreApplication.translate("MainWindow", u"Fit", None))
        self.actionCenter.setText(QCoreApplication.translate("MainWindow", u"Center", None))
        self.menuReset.setTitle(QCoreApplication.translate("MainWindow", u"Sc\u00e8ne", None))
        self.menuAjouter_Marionnette.setTitle(QCoreApplication.translate("MainWindow", u"Ajouter Marionnette", None))
        self.menuToggle_Inspector.setTitle(QCoreApplication.translate("MainWindow", u"Toggle Inspector", None))
        self.menuToggle_Timeline.setTitle(QCoreApplication.translate("MainWindow", u"Toggle Timeline", None))
        self.menuToggle_Transformation.setTitle(QCoreApplication.translate("MainWindow", u"Toggle Transformation", None))
        self.menuTimeline.setTitle(QCoreApplication.translate("MainWindow", u"Timeline", None))
        self.menuAjouter_Frame.setTitle(QCoreApplication.translate("MainWindow", u"Ajouter Frame", None))
        self.menuToggle_Loop.setTitle(QCoreApplication.translate("MainWindow", u"Toggle Loop", None))
        self.menuAnimations.setTitle(QCoreApplication.translate("MainWindow", u"Animations", None))
        self.menuCharger.setTitle(QCoreApplication.translate("MainWindow", u"Charger", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Zoom", None))

